# Generated by Django 5.1.7 on 2025-04-08 15:33

import simple_planning_poker.models.room
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_planning_poker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='code',
            field=models.CharField(default=simple_planning_poker.models.room.generate_code, max_length=6, unique=True),
        ),
    ]
