# Generated by Django 5.1.7 on 2025-04-08 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simple_planning_poker', '0003_room_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='description',
        ),
    ]
