# Generated by Django 5.1.7 on 2025-04-08 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_planning_poker', '0004_remove_story_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='title',
            field=models.CharField(default='Story', max_length=255),
        ),
    ]
