# Generated by Django 5.1.7 on 2025-05-17 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_planning_poker', '0007_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='is_revealed',
            field=models.BooleanField(default=False),
        ),
    ]
