# Generated by Django 5.1.7 on 2025-05-17 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_planning_poker', '0008_story_is_revealed'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='moderator',
            field=models.BooleanField(default=False),
        ),
    ]
