# Generated by Django 5.1.7 on 2025-06-01 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_planning_poker', '0009_userprofile_moderator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='type',
            field=models.CharField(choices=[('default', 'Default'), ('fibonacci', 'Fibonacci'), ('tshirts', 'Tshirts'), ('powers', 'Powers')], default='default', max_length=20),
        ),
        migrations.AlterField(
            model_name='story',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
