name: Keep Render Backend Warm

on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:

jobs:
  ping-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Ping backend health check
        run: |
          echo "Pinging backend at $(date)..."
          curl -s -o /dev/null -w "%{http_code}" https://simple-planning-poker-backend.onrender.com/health/
