name: Remove Old Guest Users

on:
  schedule:
    # This example runs every day at 3:00 AM UTC
    - cron: "0 3 * * *"

  # Allow manual triggering too (optional but useful)
  workflow_dispatch:

jobs:
  remove-guests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run remove old guests management command
        env:
          DJANGO_SETTINGS_MODULE: simple_planning_poker.settings
          DEBUG: ${{ secrets.DEBUG }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          python manage.py remove_old_guests
